
language: generic
sudo: required
os: osx
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - bundle install
script:
  - set -o pipefail
  - swift build
  - ./.build/debug/rock install
  - swiftlint
  - bundle exec danger
cache:
  - bundler
  - directories:
    - .rock
    - Packages
    - $HOME/.swiftenv
    - $HOME/.rock
notifications:
  email: false
